apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::147997118415:role/eksctl-expense-2-nodegroup-expense-NodeInstanceRole-W3N1aIFLgPMm
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - expense-trainee
      userarn: arn:aws:iam::147997118415:user/suresh
      username: suresh
kind: ConfigMap
metadata:
  creationTimestamp: "2025-02-26T15:27:36Z"
  name: aws-auth
  namespace: kube-system
  uid: d3b9cab4-9973-431c-a83f-33a5f112190a